{{- if and .Values.components.hasura_db.persistence.enabled (not .Values.components.hasura_db.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mint.prefix" . }}-hasura-db
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.components.hasura_db.persistence.annotations .Values.commonAnnotations }}
  annotations:
    helm.sh/resource-policy: keep
    {{- if .Values.components.hasura_db.persistence.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.components.hasura_db.persistence.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
  {{- if not (empty .Values.components.hasura_db.persistence.accessModes) }}
  {{- range .Values.components.hasura_db.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.components.hasura_db.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.components.hasura_db.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.components.hasura_db.persistence "global" .Values.global) | nindent 2 }}
  {{- if .Values.components.hasura_db.persistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.components.hasura_db.persistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
 